version: 2.1

# Define the jobs we wat to run for diamond door
jobs:
  build:
    docker:
      - image: cimg/ruby:2.7.2
      - image: cimg/postgres:15.4.0
    steps:
      - checkout
      - run: ruby --version

# Define the workflows
workflows:
  main:
    jobs:
      - build